name: Java CI with Maven

on:
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  calling-acciojob-main-action:
    uses: acciojob/acciojob-tests-action/.github/workflows/main-action.yml@main
    secrets: inherit